services:
  app:
    build:
      args:
        user: api
        uid: 1000
      context: ./
      dockerfile: ./.docker/php/Dockerfile
    image: ${APP_NAME}-api
    container_name: ${APP_NAME}-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - docker_network

  db:
    container_name: ${APP_NAME}-db
    image: postgres:14
    volumes:
      - ./.docker/postgres/pgdata:/var/lib/postgresql/data
      - ./.docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - docker_network

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - docker_network

  redis:
    container_name: ${APP_NAME}-redis
    image: redis:6.2-alpine
    environment:
      REDIS_USERNAME: redis
      REDIS_PASSWORD: redis
    command: redis-server --requirepass "${REDIS_PASSWORD}" --appendonly yes
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge
